version: '3.8'
services:
  dev-database:
    image: postgres:15.0
    container_name: express-db
    ports:
      - 5437:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: testdb
    networks:
      - nestjs-network
networks:
  nestjs-network: #run docker: docker compose up -d
